import type { Metadata, Viewport } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import toast, { Toaster } from 'react-hot-toast';
// internal
import { Footer, NavBar } from '@/components'
import { NFTMarketplaceProvider } from '@/context/NFTMarketplaceContext'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'NFT Market',
    description: 'Generated by Neil',
}

export const viewport: Viewport = {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    minimumScale: 1,
    userScalable: false,
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <NFTMarketplaceProvider>
                    <NavBar />
                    {children}
                    <Footer />
                    <Toaster />
                </NFTMarketplaceProvider>
            </body>
        </html>
    )
}
